# From: https://github.com/marketplace/actions/compile-arduino-sketches
# Uses: https://github.com/arduino/compile-sketches

# This workflow only compiles for AVR

name: Arduino Compile Sketches

on: 
  push:
  workflow_dispatch:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string

jobs:
  compile-sketches: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup-python (when running locally for nektos/act compatibility)
        if: ${{ env.ACT }}
        uses: actions/setup-python@v4
        with:
          python-version: '>=3.11'
      - name: Install Poetry (when running locally for nektos/act compatibility)
        if: ${{ env.ACT }}
        uses: snok/install-poetry@v1
      - name: Install pipx (when running locally for nektos/act compatibility)
        if: ${{ env.ACT }}
        run: pip install pipx
      - uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - .
          verbose: true
          enable-warnings-report: true
          libraries: |
            - source-path: ./
            # Add library dependencies here: 
            # - source-url: https://github.com/<owner-name>/<repo-name>.git
            # - name: name-of-library-registered-with-arduino-library-manager
      - name: Print the job summary
        if: ${{ inputs.message }}
        run: |
          echo ${{ inputs.message }} >$GITHUB_STEP_SUMMARY
